version: "3.8"

services:
  # MOVIES
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ~/apps/freemedia/config/radarr:/config
      - ~/downloads/movies:/movies
      - ~/downloads:/downloads
    ports:
      - ${RADARR_PORT}:7878
    restart: unless-stopped

  # TV SHOWS
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ~/apps/freemedia/config/sonarr:/config
      - ~/downloads/tv:/tv
      - ~/downloads:/downloads
    ports:
      - ${SONARR_PORT}:8989
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ~/apps/freemedia/config/prowlarr:/config
    ports:
      - ${PROWLARR_PORT}:9696
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=8080
    volumes:
      - ~/apps/freemedia/config/qbittorrent:/config
      - ~/downloads:/downloads
    ports:
      - ${QBITTORRENT_PORT}:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped

  organizr:
    image: organizr/organizr:latest
    container_name: organizr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ~/apps/freemedia/config/organizr:/config
    ports:
      - ${ORGANIZR_PORT}:80
    restart: unless-stopped